services:
  quadruped-ws:
    image: quadruped-sdk:latest
    build:
      context: .
    network_mode: host
    environment:
      DOG_IP: 192.168.96.2
      DOG_PORT: 8080
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 9001
    command: ["ws"]

  quadruped-ws-mock:
    image: quadruped-sdk:latest
    build:
      context: .
    network_mode: host
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 9101
    command: ["ws-mock"]
    profiles:
      - mock
